### ISSUE TITLE
Characteristic Typo

### ISSUE THREAD

**Issue by Emdien** [tecnomod-um/oquo#1]
ModificationStabilityCharacteristic is currently named "ModificaionStabilityCharacteristic"

Hard to spot, but the typo is Modifica**T**ion is currently Modifica ion

The autogenerated label is also wrong, but fixing the IRI should also fix that

**Comment by fanavarro** [comment]
Fixed in https://github.com/tecnomod-um/oquo/commit/780ec934dc1682c8cb2f9a55570e0542f34823ea.
